import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/components/navbar.jsx';
import Button from 'react-bootstrap/Button';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <NavBar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div>
      <div style={{
            zIndex: -10,
            position: 'fixed',
            height: '100vh',
            width: '100vw'
        }}>
            <Image
                src="/library-book-bookshelf-read.jpg"
                alt="Nice Background"
                layout="fill"
                objectFit='cover'
            ></Image>
        </div>
        <div style={{
            margin: 'auto',
            height: '100vh',
            width: '90vw',
            backgroundColor: "rgba(0,0,0,0.7)"
        }}>

            <p style={{color: "#FFFFFF", textAlign: "center"}}>
              by Ekkasith Singmaneechai 6213934&nbsp;<br />
              Anwar Rasheed 6215106
            </p>

          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
            <span style={{color: "#FFFFFF", textAlign: "center"}}><h1>CRUD Novel Web Application</h1>
            <br />
            <br />
            <Button variant="success" size="sl" style={{ marginLeft: '50rem' }} href={`/collections`}> Go Browse Novel </Button>
            </span>
            
          </div>
        </div>
      
    </>
  )
}